namespace Libgit2Bindings;

public interface IGitPathspecMathList : IDisposable
{
  /// <summary>
  /// Get the number of pathspec items that did not match.
  /// </summary>
  /// <remarks>
  /// This will be zero unless you passed <see cref="GitPathspecFlags.FindFailures"/> 
  /// when generating the git_pathspec_match_list.
  /// </remarks>
  nuint FailedEntrycount { get; }

  /// <summary>
  /// Get an original pathspec string that had no matches.
  /// </summary>
  /// <remarks>
  /// This will be return null for positions out of range.
  /// </remarks>
  /// <param name="index">The index into the failed items</param>
  /// <returns>The pathspec pattern that didn't match anything</returns>
  string? FailedEntry(nuint index);

  /// <summary>
  /// Get the number of items in a match list.
  /// </summary>
  nuint Entrycount { get; }

  /// <summary>
  /// Get a matching filename by position.
  /// </summary>
  /// <remarks>
  /// This routine cannot be used if the match list was generated by <see cref="IGitPathspec.MatchDiff"/>. 
  /// If so, it will always return null.
  /// </remarks>
  /// <param name="index">The index into the list</param>
  /// <returns>The filename of the match</returns>
  string? Entry(nuint index);

  /// <summary>
  /// Get a matching diff delta by position.
  /// </summary>
  /// <remarks>
  /// This routine can only be used if the match list was generated by <see cref="IGitPathspec.MatchDiff"/>. 
  /// Otherwise it will always return null.
  /// </remarks>
  /// <param name="index">The index into the list</param>
  /// <returns>The filename of the match</returns>
  GitDiffDelta? DiffEntry(nuint index);
}
